"""Adiciona campos aos modelos

Revision ID: 28f415d92b9b
Revises: 6c4cb49c3186
Create Date: 2025-10-27 16:38:58.207579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f415d92b9b'
down_revision: Union[str, Sequence[str], None] = '6c4cb49c3186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartoes', sa.Column('validade', sa.Date(), nullable=False))
    op.add_column('cartoes', sa.Column('cvv', sa.String(), nullable=False))
    op.add_column('contas', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('emprestimos', sa.Column('data_inicio', sa.Date(), nullable=False))
    op.add_column('investimentos', sa.Column('data_aplicacao', sa.Date(), nullable=False))
    op.add_column('notificacoes', sa.Column('data_envio', sa.DateTime(), nullable=True))
    op.add_column('pagamentos', sa.Column('descricao', sa.String(), nullable=True))
    op.add_column('transacoes', sa.Column('conta_id', sa.UUID(), nullable=False))
    op.add_column('transacoes', sa.Column('descricao', sa.String(), nullable=True))
    op.drop_constraint(op.f('transacoes_conta_origem_id_fkey'), 'transacoes', type_='foreignkey')
    op.drop_constraint(op.f('transacoes_conta_destino_id_fkey'), 'transacoes', type_='foreignkey')
    op.create_foreign_key(None, 'transacoes', 'contas', ['conta_id'], ['id'])
    op.drop_column('transacoes', 'conta_destino_id')
    op.drop_column('transacoes', 'conta_origem_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('conta_origem_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transacoes', sa.Column('conta_destino_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.create_foreign_key(op.f('transacoes_conta_destino_id_fkey'), 'transacoes', 'contas', ['conta_destino_id'], ['id'])
    op.create_foreign_key(op.f('transacoes_conta_origem_id_fkey'), 'transacoes', 'contas', ['conta_origem_id'], ['id'])
    op.drop_column('transacoes', 'descricao')
    op.drop_column('transacoes', 'conta_id')
    op.drop_column('pagamentos', 'descricao')
    op.drop_column('notificacoes', 'data_envio')
    op.drop_column('investimentos', 'data_aplicacao')
    op.drop_column('emprestimos', 'data_inicio')
    op.drop_column('contas', 'data_criacao')
    op.drop_column('cartoes', 'cvv')
    op.drop_column('cartoes', 'validade')
    # ### end Alembic commands ###
