"""create tables

Revision ID: 6c4cb49c3186
Revises: 71fb26edc707
Create Date: 2025-10-26 11:08:36.568403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4cb49c3186'
down_revision: Union[str, Sequence[str], None] = '71fb26edc707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_conta', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_conta')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('limite', sa.Float(), nullable=True),
    sa.Column('fatura_atual', sa.Float(), nullable=True),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('emprestimos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('taxa_juros', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor_aplicado', sa.Float(), nullable=False),
    sa.Column('rentabilidade', sa.Float(), nullable=True),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('codigo_barras', sa.String(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_origem_id', sa.UUID(), nullable=False),
    sa.Column('conta_destino_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_destino_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['conta_origem_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('pagamentos')
    op.drop_table('investimentos')
    op.drop_table('emprestimos')
    op.drop_table('cartoes')
    op.drop_table('notificacoes')
    op.drop_table('contas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
