"""initial tables

Revision ID: 7fae6f0bd5ba
Revises: 
Create Date: 2026-01-06 17:10:46.263647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fae6f0bd5ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.String(length=10), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_conta', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_conta')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('cvv', sa.String(), nullable=False),
    sa.Column('limite', sa.Float(), nullable=False),
    sa.Column('fatura_atual', sa.Float(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('emprestimos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('taxa_juros', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor_aplicado', sa.Float(), nullable=False),
    sa.Column('data_aplicacao', sa.Date(), nullable=False),
    sa.Column('rentabilidade', sa.Float(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('codigo_barras', sa.String(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('pagamentos')
    op.drop_table('investimentos')
    op.drop_table('emprestimos')
    op.drop_table('cartoes')
    op.drop_table('notificacoes')
    op.drop_table('contas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
